resilience4j:
  ratelimiter:
    instances:
      AuthController:
        limit-for-period: 5
        limit-refresh-period: 15s
        timeout-duration: 30s
      EmailController:
        limit-for-period: 4
        limit-refresh-period: 2m
        timeout-duration: 30s
      RoomController:
        limit-for-period: 3
        limit-refresh-period: 1m
        timeout-duration: 30s
      CategoryController:
        limit-for-period: 4
        limit-refresh-period: 1m
        timeout-duration: 30s
