server:
  port: 8000
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types:
      - application/json
      - text/html
      - text/css
      - application/javascript
      - text/plain
      - application/xml
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false
        same-site: lax
  tomcat:
    threads:
      max: 200
      min-spare: 20
    connection-timeout: 20000
    max-connections: 8192
    accept-count: 100
    max-http-form-post-size: 2MB

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

server:
  servlet:
    session:
      cookie:
        secure: false

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: strict
  tomcat:
    threads:
      max: 300
      min-spare: 50
    max-connections: 10000