spring:
  application:
    name: engly-server

  profiles:
    active: dev
    include:
      - database
      - security
      - monitoring
      - server
      - ratelimiter

  threads:
    virtual:
      enabled: true

  main:
    allow-bean-definition-overriding: true

spring.config.import:
  - optional:classpath:config/database.yml
  - optional:classpath:config/security.yml
  - optional:classpath:config/monitoring.yml
  - optional:classpath:config/server.yml
  - optional:classpath:config/ratelimiter.yml