resilience4j:
  ratelimiter:
    instances:
      AuthController:
        limit-for-period: 3
        limit-refresh-period: 60s
        timeout-duration: 0
      CategoryController:
        limit-for-period: 3
        limit-refresh-period: 30s
        timeout-duration: 0
      RoomController:
        limit-for-period: 8
        limit-refresh-period: 30s
        timeout-duration: 0
      EmailController:
        limit-for-period: 3
        limit-refresh-period: 5m
        timeout-duration: 0
      PublicController:
        limit-for-period: 1
        limit-refresh-period: 5s
        timeout-duration: 0